ALTER TABLE submissions DROP CONSTRAINT IF EXISTS submissions_status_check;
ALTER TABLE submissions ADD CONSTRAINT submissions_status_check
  CHECK (status IN ('PENDING','QUEUED','LEASED','RETRYABLE_FAILURE','PROTOCOL_FAILURE','CANCELLED','EXECUTION_COMPLETED','SYNTHETIC_COMPLETED'));
