CREATE SEQUENCE IF NOT EXISTS problems_public_number_seq AS bigint START WITH 1;
ALTER TABLE problems ADD COLUMN IF NOT EXISTS public_number bigint;
WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY created_at ASC, id ASC)::bigint AS number
  FROM problems WHERE public_number IS NULL
)
UPDATE problems p SET public_number=o.number
FROM ordered o WHERE p.id=o.id;
SELECT setval(
  'problems_public_number_seq',
  COALESCE((SELECT MAX(public_number) FROM problems), 1),
  EXISTS (SELECT 1 FROM problems)
);
ALTER TABLE problems ALTER COLUMN public_number SET DEFAULT nextval('problems_public_number_seq');
ALTER TABLE problems ALTER COLUMN public_number SET NOT NULL;
ALTER SEQUENCE problems_public_number_seq OWNED BY problems.public_number;
CREATE UNIQUE INDEX IF NOT EXISTS problems_public_number_idx ON problems(public_number);
ALTER TABLE problem_revisions ADD COLUMN IF NOT EXISTS public_number bigint;
UPDATE problem_revisions r SET public_number=p.public_number
FROM problems p WHERE p.id=r.problem_id AND r.public_number IS NULL;
ALTER TABLE problem_revisions ALTER COLUMN public_number SET NOT NULL;
CREATE INDEX IF NOT EXISTS problem_revisions_public_number_idx ON problem_revisions(public_number);
ALTER TABLE problems ADD COLUMN IF NOT EXISTS source_type text NOT NULL DEFAULT 'CREATOR';
ALTER TABLE problem_revisions ADD COLUMN IF NOT EXISTS source_type text NOT NULL DEFAULT 'CREATOR';
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='problems_source_type_check') THEN
    ALTER TABLE problems ADD CONSTRAINT problems_source_type_check CHECK (source_type IN ('CREATOR','EXTERNAL','IMPORT'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='problem_revisions_source_type_check') THEN
    ALTER TABLE problem_revisions ADD CONSTRAINT problem_revisions_source_type_check CHECK (source_type IN ('CREATOR','EXTERNAL','IMPORT'));
  END IF;
END $$;

CREATE SEQUENCE IF NOT EXISTS submission_evaluations_public_number_seq AS bigint START WITH 0 MINVALUE 0;
ALTER TABLE submission_evaluations ADD COLUMN IF NOT EXISTS public_number bigint;
WITH ordered AS (
  SELECT submission_id, evaluation_generation,
    (row_number() OVER (ORDER BY created_at ASC, submission_id ASC, evaluation_generation ASC) - 1)::bigint AS number
  FROM submission_evaluations WHERE public_number IS NULL
)
UPDATE submission_evaluations e SET public_number=o.number
FROM ordered o
WHERE e.submission_id=o.submission_id AND e.evaluation_generation=o.evaluation_generation;
SELECT setval(
  'submission_evaluations_public_number_seq',
  COALESCE((SELECT MAX(public_number) FROM submission_evaluations), 0),
  EXISTS (SELECT 1 FROM submission_evaluations)
);
ALTER TABLE submission_evaluations ALTER COLUMN public_number SET DEFAULT nextval('submission_evaluations_public_number_seq');
ALTER TABLE submission_evaluations ALTER COLUMN public_number SET NOT NULL;
ALTER SEQUENCE submission_evaluations_public_number_seq OWNED BY submission_evaluations.public_number;
CREATE UNIQUE INDEX IF NOT EXISTS submission_evaluations_public_number_idx ON submission_evaluations(public_number);

CREATE TABLE IF NOT EXISTS tags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  normalized_key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS problem_tags (
  problem_id text NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
  tag_id bigint NOT NULL REFERENCES tags(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(problem_id, tag_id)
);
CREATE INDEX IF NOT EXISTS problem_tags_tag_idx ON problem_tags(tag_id, problem_id);
CREATE INDEX IF NOT EXISTS problem_tags_problem_idx ON problem_tags(problem_id, tag_id);
