ALTER TABLE tags ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS display_order integer;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS is_active boolean;
UPDATE tags SET slug = COALESCE(slug, normalized_key), name = COALESCE(name, display_name), category = COALESCE(category, '未分类'), display_order = COALESCE(display_order, 0), is_active = COALESCE(is_active, TRUE);
ALTER TABLE tags ALTER COLUMN slug SET NOT NULL;
ALTER TABLE tags ALTER COLUMN name SET NOT NULL;
ALTER TABLE tags ALTER COLUMN category SET NOT NULL;
ALTER TABLE tags ALTER COLUMN display_order SET NOT NULL;
ALTER TABLE tags ALTER COLUMN display_order SET DEFAULT 0;
ALTER TABLE tags ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE tags ALTER COLUMN is_active SET DEFAULT TRUE;
CREATE UNIQUE INDEX IF NOT EXISTS tags_slug_idx ON tags(slug);
CREATE UNIQUE INDEX IF NOT EXISTS tags_category_name_idx ON tags(category, name);
CREATE INDEX IF NOT EXISTS tags_catalog_order_idx ON tags(category, display_order, id);
CREATE INDEX IF NOT EXISTS problem_tags_problem_idx ON problem_tags(problem_id, tag_id);
CREATE INDEX IF NOT EXISTS problem_tags_tag_idx ON problem_tags(tag_id, problem_id);
INSERT INTO tags (slug, name, category, display_order, is_active, normalized_key, display_name)
VALUES
('enumeration','枚举','基础算法',10,TRUE,'enumeration','枚举'),('simulation','模拟','基础算法',20,TRUE,'simulation','模拟'),('sorting','排序','基础算法',30,TRUE,'sorting','排序'),('prefix-sum','前缀和','基础算法',40,TRUE,'prefix-sum','前缀和'),('difference-array','差分','基础算法',50,TRUE,'difference-array','差分'),('two-pointers','双指针','基础算法',60,TRUE,'two-pointers','双指针'),('greedy','贪心','基础算法',70,TRUE,'greedy','贪心'),('bit-manipulation','位运算','基础算法',80,TRUE,'bit-manipulation','位运算'),
('linked-list','链表','数据结构',10,TRUE,'linked-list','链表'),('stack','栈','数据结构',20,TRUE,'stack','栈'),('queue','队列','数据结构',30,TRUE,'queue','队列'),('hash-table','哈希表','数据结构',40,TRUE,'hash-table','哈希表'),('heap','堆','数据结构',50,TRUE,'heap','堆'),('disjoint-set-union','并查集','数据结构',60,TRUE,'disjoint-set-union','并查集'),('monotonic-stack','单调栈','数据结构',70,TRUE,'monotonic-stack','单调栈'),('fenwick-tree','树状数组','数据结构',80,TRUE,'fenwick-tree','树状数组'),('segment-tree','线段树','数据结构',90,TRUE,'segment-tree','线段树'),
('binary-search','二分查找','搜索',10,TRUE,'binary-search','二分查找'),('depth-first-search','DFS','搜索',20,TRUE,'depth-first-search','DFS'),('breadth-first-search','BFS','搜索',30,TRUE,'breadth-first-search','BFS'),('backtracking','回溯','搜索',40,TRUE,'backtracking','回溯'),('divide-and-conquer','分治','搜索',50,TRUE,'divide-and-conquer','分治'),
('shortest-path','最短路','图论',10,TRUE,'shortest-path','最短路'),('dijkstra','Dijkstra','图论',20,TRUE,'dijkstra','Dijkstra'),('floyd','Floyd','图论',30,TRUE,'floyd','Floyd'),('minimum-spanning-tree','最小生成树','图论',40,TRUE,'minimum-spanning-tree','最小生成树'),('topological-sort','拓扑排序','图论',50,TRUE,'topological-sort','拓扑排序'),('strongly-connected-components','强连通分量','图论',60,TRUE,'strongly-connected-components','强连通分量'),('network-flow','网络流','图论',70,TRUE,'network-flow','网络流'),('bipartite-graph','二分图','图论',80,TRUE,'bipartite-graph','二分图'),('bipartite-matching','二分图匹配','图论',90,TRUE,'bipartite-matching','二分图匹配'),
('dynamic-programming','动态规划','动态规划',10,TRUE,'dynamic-programming','动态规划'),('knapsack','背包','动态规划',20,TRUE,'knapsack','背包'),('linear-dp','线性DP','动态规划',30,TRUE,'linear-dp','线性DP'),('interval-dp','区间DP','动态规划',40,TRUE,'interval-dp','区间DP'),('tree-dp','树形DP','动态规划',50,TRUE,'tree-dp','树形DP'),('bitmask-dp','状压DP','动态规划',60,TRUE,'bitmask-dp','状压DP'),('digit-dp','数位DP','动态规划',70,TRUE,'digit-dp','数位DP'),('longest-common-subsequence','最长公共子序列','动态规划',80,TRUE,'longest-common-subsequence','最长公共子序列'),('longest-increasing-subsequence','最长上升子序列','动态规划',90,TRUE,'longest-increasing-subsequence','最长上升子序列'),
('string-matching','字符串匹配','字符串',10,TRUE,'string-matching','字符串匹配'),('kmp','KMP','字符串',20,TRUE,'kmp','KMP'),('trie','Trie','字符串',30,TRUE,'trie','Trie'),('aho-corasick','AC自动机','字符串',40,TRUE,'aho-corasick','AC自动机'),('string-hashing','字符串哈希','字符串',50,TRUE,'string-hashing','字符串哈希'),('manacher','Manacher','字符串',60,TRUE,'manacher','Manacher'),('suffix-array','后缀数组','字符串',70,TRUE,'suffix-array','后缀数组'),('suffix-automaton','后缀自动机','字符串',80,TRUE,'suffix-automaton','后缀自动机'),
('number-theory','数论','数学',10,TRUE,'number-theory','数论'),('combinatorics','组合数学','数学',20,TRUE,'combinatorics','组合数学'),('prime-numbers','素数','数学',30,TRUE,'prime-numbers','素数'),('sieve','筛法','数学',40,TRUE,'sieve','筛法'),('gcd','最大公约数','数学',50,TRUE,'gcd','最大公约数'),('extended-gcd','扩展欧几里得','数学',60,TRUE,'extended-gcd','扩展欧几里得'),('fast-exponentiation','快速幂','数学',70,TRUE,'fast-exponentiation','快速幂'),('modular-inverse','逆元','数学',80,TRUE,'modular-inverse','逆元'),('matrix','矩阵','数学',90,TRUE,'matrix','矩阵'),('game-theory','博弈论','数学',100,TRUE,'game-theory','博弈论'),('fft','FFT','数学',110,TRUE,'fft','FFT'),('ntt','NTT','数学',120,TRUE,'ntt','NTT'),
('binary-tree','二叉树','树',10,TRUE,'binary-tree','二叉树'),('binary-search-tree','二叉搜索树','树',20,TRUE,'binary-search-tree','二叉搜索树'),('lowest-common-ancestor','LCA','树',30,TRUE,'lowest-common-ancestor','LCA'),('heavy-light-decomposition','树链剖分','树',40,TRUE,'heavy-light-decomposition','树链剖分'),('tree-difference','树上差分','树',50,TRUE,'tree-difference','树上差分'),('centroid-decomposition','点分治','树',60,TRUE,'centroid-decomposition','点分治'),('virtual-tree','虚树','树',70,TRUE,'virtual-tree','虚树'),
('computational-geometry','计算几何','计算几何',10,TRUE,'computational-geometry','计算几何'),('convex-hull','凸包','计算几何',20,TRUE,'convex-hull','凸包'),('sweep-line','扫描线','计算几何',30,TRUE,'sweep-line','扫描线'),('segment-intersection','线段相交','计算几何',40,TRUE,'segment-intersection','线段相交'),('rotating-calipers','旋转卡壳','计算几何',50,TRUE,'rotating-calipers','旋转卡壳'),('precision','精度处理','计算几何',60,TRUE,'precision','精度处理'),
('coordinate-compression','离散化','高级技巧',10,TRUE,'coordinate-compression','离散化'),('sqrt-decomposition','分块','高级技巧',20,TRUE,'sqrt-decomposition','分块'),('mo-algorithm','莫队','高级技巧',30,TRUE,'mo-algorithm','莫队'),('cdq-divide-and-conquer','CDQ分治','高级技巧',40,TRUE,'cdq-divide-and-conquer','CDQ分治'),('parallel-binary-search','整体二分','高级技巧',50,TRUE,'parallel-binary-search','整体二分'),('small-to-large','启发式合并','高级技巧',60,TRUE,'small-to-large','启发式合并'),('linear-basis','线性基','高级技巧',70,TRUE,'linear-basis','线性基'),('inclusion-exclusion','容斥原理','高级技巧',80,TRUE,'inclusion-exclusion','容斥原理')
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name, category=EXCLUDED.category, display_order=EXCLUDED.display_order, is_active=EXCLUDED.is_active;
