services:
  postgres:
    ports:
      - '127.0.0.1:${OJPLATFORM_POSTGRES_PORT:-55432}:5432'

  redis:
    ports:
      - '127.0.0.1:${OJPLATFORM_REDIS_PORT:-56379}:6379'

  minio:
    ports:
      - '127.0.0.1:${OJPLATFORM_MINIO_PORT:-59000}:9000'
      - '127.0.0.1:${OJPLATFORM_MINIO_CONSOLE_PORT:-59001}:9001'
