import type { HomeworkDashboardFixture } from './types.js';

const lessonTitles = [
  '复杂度与大 O 表示',
  '数组与模拟',
  '链表',
  '栈与队列',
  '哈希表',
  '字符串',
  '双指针',
  '滑动窗口',
  '递归与分治',
  '动态规划（一）',
  '动态规划（二）',
  '贪心算法',
  '二分查找',
  '排序算法',
  '图的基本概念',
  '最短路算法',
  '最小生成树',
  '树和树形 DP',
  '搜索与回溯',
  '字符串匹配',
  '经典数据结构',
  '并查集',
  '综合训练应用',
  '课程总结',
];

export const homeworkDashboardFixture: HomeworkDashboardFixture = {
  courseTitle: '算法基础',
  courseCount: 24,
  completedLessons: 8,
  lessons: lessonTitles.map((title, index) => ({
    number: index + 1,
    title,
    completed: index === 0 ? 3 : index === 1 ? 2 : index === 2 ? 1 : 0,
    total: 3,
    state: index === 0 ? 'completed' : index === 1 ? 'current' : 'pending',
  })),
  priorityTasks: [
    {
      lesson: 6,
      problemId: 'P1067',
      title: '字符串匹配',
      tags: ['字符串', 'KMP', '基础'],
      dueAt: '2024-10-22 23:59',
      deadlineLabel: '截止 2 天后',
    },
    {
      lesson: 7,
      problemId: 'P1042',
      title: '二分查找',
      tags: ['二分查找', '数组', '基础'],
      dueAt: '2024-10-23 23:59',
      deadlineLabel: '截止 3 天后',
    },
    {
      lesson: 8,
      problemId: 'P1078',
      title: '背包问题',
      tags: ['动态规划', '背包', '经典'],
      dueAt: '2024-10-25 23:59',
      deadlineLabel: '截止 5 天后',
    },
    {
      lesson: 9,
      problemId: 'P1092',
      title: '区间和',
      tags: ['前缀和', '数组', '思维'],
      dueAt: '2024-10-26 23:59',
      deadlineLabel: '截止 2 天后',
    },
    {
      lesson: 10,
      problemId: 'P1030',
      title: '数组的累和',
      tags: ['数组', '前缀和', '简单'],
      dueAt: '2024-10-28 23:59',
      deadlineLabel: '截止 4 天后',
    },
    {
      lesson: 11,
      problemId: 'P1000',
      title: '两数之和',
      tags: ['数组', '哈希表', '基础'],
      dueAt: '2024-10-29 23:59',
      deadlineLabel: '截止 5 天后',
    },
  ],
  overdueTasks: [
    {
      lesson: 3,
      problemId: 'P1024',
      title: '图的遍历',
      tags: ['图论', '搜索', '基础'],
      dueAt: '2024-10-20 23:59',
      deadlineLabel: '已过期',
      overdueLabel: '已拖欠 2 天',
      actionLabel: '立即补交',
    },
    {
      lesson: 4,
      problemId: 'P1000',
      title: '两数之和',
      tags: ['数组', '哈希表', '基础'],
      dueAt: '2024-10-18 23:59',
      deadlineLabel: '已过期',
      overdueLabel: '已拖欠 5 天',
      actionLabel: '继续补做',
    },
  ],
  reminders: [
    {
      lesson: 6,
      problemId: 'P1067',
      title: '字符串匹配',
      dueAt: '2024-10-22 23:59',
      timing: '2 天后',
      tone: 'danger',
    },
    {
      lesson: 7,
      problemId: 'P1042',
      title: '二分查找',
      dueAt: '2024-10-23 23:59',
      timing: '3 天后',
      tone: 'warning',
    },
    {
      lesson: 8,
      problemId: 'P1078',
      title: '背包问题',
      dueAt: '2024-10-25 23:59',
      timing: '5 天后',
      tone: 'info',
    },
    {
      lesson: 3,
      problemId: 'P1024',
      title: '图的遍历',
      dueAt: '2024-10-26 23:59',
      timing: '即将截止',
      tone: 'danger',
    },
  ],
};
