import { useEffect, useRef, useState, type FormEvent } from 'react';
import type { ApiClient, AuthenticatedUser, DiscussionAuthor, DiscussionComment, DiscussionPost } from '../../services/api.js';
import { MarkdownToolbar } from '../../components/ProblemEditor.js';
import { DiscussionRenderer } from './DiscussionRenderer.js';

function AuthorLink({ author, navigate }: { author: DiscussionAuthor | undefined; navigate: (path: string) => void }) {
  const safe = author ?? { username: 'deleted-user', displayName: 'Deleted User' };
  return <a className="discussion-author" href={`/profiles/${encodeURIComponent(safe.username)}`} onClick={(event) => { event.preventDefault(); navigate(`/profiles/${encodeURIComponent(safe.username)}`); }}><span className="discussion-author-avatar" aria-hidden="true">{safe.displayName.slice(0, 1).toUpperCase()}</span><span>{safe.displayName}</span><small>@{safe.username}</small></a>;
}

export function DiscussionHome({ api, navigate, user }: { api: ApiClient; navigate: (path: string) => void; user: AuthenticatedUser | null }) {
  const [posts, setPosts] = useState<DiscussionPost[]>([]); const [error, setError] = useState('');
  useEffect(() => { void api.discussionPosts('limit=20').then(r => setPosts(r.items)).catch(e => setError(e instanceof Error ? e.message : '加载失败')); }, [api]);
  return <section className="discussion-page"><header className="page-heading"><div><p className="eyebrow">Discussion / 讨论</p><h1>分享想法，记录学习</h1><p>文章、公告与社区讨论。</p></div>{user && <button onClick={() => navigate('/discussion/new')}>写文章</button>}</header>{error && <p role="alert">{error}</p>}<div className="discussion-list">{posts.map(post => <article className="discussion-list-item" key={post.id}><span className={post.type === 'ANNOUNCEMENT' ? 'discussion-type announcement' : 'discussion-type'}>{post.type === 'ANNOUNCEMENT' ? '公告' : '文章'}</span><h2><a href={`/discussion/${post.publicId}`} onClick={e => { e.preventDefault(); navigate(`/discussion/${post.publicId}`); }}>{post.title}</a></h2><AuthorLink author={post.author} navigate={navigate} /><p>{post.summary || post.contentMarkdown.slice(0, 160)}</p><small>{post.viewCount} 浏览 · {post.likeCount} 点赞 · {post.commentCount} 评论</small></article>)}</div>{!posts.length && !error && <p>暂无已发布内容。</p>}</section>;
}

export function DiscussionPostPage({ api, navigate, id, user }: { api: ApiClient; navigate: (path: string) => void; id: string; user: AuthenticatedUser | null }) {
  const [post, setPost] = useState<DiscussionPost | null>(null); const [comments, setComments] = useState<DiscussionComment[]>([]); const [comment, setComment] = useState(''); const [message, setMessage] = useState(''); const [editing, setEditing] = useState<string | null>(null); const [editValue, setEditValue] = useState('');
  const refreshComments = () => { if (post) void api.discussionComments(post.id, 'limit=20').then(result => setComments(result.items)).catch(error => setMessage(error instanceof Error ? error.message : '评论加载失败')); };
  const refreshPost = () => { if (post) void api.discussionPost(post.id).then(setPost).catch(error => setMessage(error instanceof Error ? error.message : '文章加载失败')); };
  useEffect(() => { void api.discussionPost(id).then(setPost).catch(e => setMessage(e instanceof Error ? e.message : '加载失败')); }, [api, id]);
  useEffect(() => { refreshComments(); }, [post?.id]);
  if (!post) return <section className="discussion-page"><p role="status">{message || '加载中…'}</p></section>;
  const submitComment = async (e: FormEvent) => { e.preventDefault(); if (!comment.trim()) return; try { await api.createDiscussionComment(post.id, comment); setComment(''); setMessage('评论已发布'); refreshComments(); refreshPost(); } catch (err) { setMessage(err instanceof Error ? err.message : '评论失败'); } };
  const saveComment = async (commentId: string) => { try { await api.updateDiscussionComment(commentId, editValue); setEditing(null); setMessage('评论已更新'); refreshComments(); } catch (error) { setMessage(error instanceof Error ? error.message : '更新失败'); } };
  return <article className="discussion-page discussion-detail"><span className={post.type === 'ANNOUNCEMENT' ? 'discussion-type announcement' : 'discussion-type'}>{post.type === 'ANNOUNCEMENT' ? '官方公告' : '文章'}</span><h1>{post.title}</h1><AuthorLink author={post.author} navigate={navigate} /><p className="discussion-meta">发布于 {new Date(post.publishedAt ?? post.createdAt).toLocaleString()} · 更新于 {new Date(post.updatedAt).toLocaleString()} · {post.viewCount} 浏览</p><DiscussionRenderer content={post.contentMarkdown} /><div className="discussion-actions"><button onClick={() => void api.likeDiscussionPost(post.id).then(() => api.discussionPost(post.id)).then(setPost)}>点赞 ({post.likeCount})</button></div><section className="discussion-comments"><div className="discussion-comments-heading"><h2>评论 ({post.commentCount})</h2><button type="button" onClick={refreshComments}>刷新评论</button></div>{comments.map(item => <article className="discussion-comment" key={item.id}><AuthorLink author={item.author} navigate={navigate} />{editing === item.id ? <><textarea value={editValue} onChange={event => setEditValue(event.target.value)} /><button onClick={() => void saveComment(item.id)}>保存</button><button onClick={() => setEditing(null)}>取消</button></> : <><DiscussionRenderer content={item.contentMarkdown} /></>}</article>)}{user ? <form onSubmit={submitComment}><textarea value={comment} onChange={e => setComment(e.target.value)} placeholder="写下你的评论" /><button type="submit">发布评论</button></form> : <p>登录后参与评论。</p>}{message && <p role="status">{message}</p>}</section></article>;
}

export function DiscussionEditor({ api, navigate, id, user }: { api: ApiClient; navigate: (path: string) => void; id?: string; user: AuthenticatedUser | null }) {
  const [title, setTitle] = useState(''); const [summary, setSummary] = useState(''); const [content, setContent] = useState(''); const [message, setMessage] = useState(''); const textareaRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { if (id) void api.discussionPost(id).then(p => { setTitle(p.title); setSummary(p.summary ?? ''); setContent(p.contentMarkdown); }).catch(() => setMessage('文章加载失败')); }, [api, id]);
  const save = async (status: 'DRAFT' | 'PUBLISHED') => { try { const p = id ? await api.updateDiscussionPost(id, { title, summary, contentMarkdown: content }) : await api.createDiscussionPost({ title, summary, contentMarkdown: content, status }); if (status === 'PUBLISHED' && id) await api.publishDiscussionPost(p.id); setMessage(status === 'PUBLISHED' ? '已发布' : '草稿已保存'); if (status === 'PUBLISHED') navigate(`/discussion/${p.publicId}`); } catch (e) { setMessage(e instanceof Error ? e.message : '保存失败'); } };
  if (!user) return <p>请先登录。</p>;
  return <section className="discussion-page discussion-editor"><h1>{id ? '编辑文章' : '写文章'}</h1><input value={title} onChange={e => setTitle(e.target.value)} placeholder="标题" /><input value={summary} onChange={e => setSummary(e.target.value)} placeholder="摘要（可选）" /><MarkdownToolbar textareaRef={textareaRef} value={content} onChange={setContent} disabled={false} /><div className="discussion-editor-split"><textarea ref={textareaRef} value={content} onChange={e => setContent(e.target.value)} placeholder="Markdown 内容" /><div className="discussion-preview"><DiscussionRenderer content={content || '*预览*'} /></div></div><div className="discussion-actions"><button onClick={() => void save('DRAFT')}>保存草稿</button><button onClick={() => void save('PUBLISHED')}>发布</button></div>{message && <p role="status">{message}</p>}</section>;
}
