param(
  [Parameter(Mandatory=$true)][string]$Distro,
  [Parameter(Mandatory=$true)][string]$Project,
  [Parameter(Mandatory=$true)][string]$Service,
  [Parameter(Mandatory=$true)][int]$Port
)
$ErrorActionPreference = 'Stop'
function Wsl([string[]]$Arguments) { $out=& wsl.exe @('-d',$Distro,'--user','root','--') @Arguments 2>&1; if($LASTEXITCODE -ne 0){throw "WSL_DOCKER_INSPECTION_FAILED: $($out -join ' ')"}; return $out }
function Tcp([int]$P) { try { $c=[Net.Sockets.TcpClient]::new(); $t=$c.ConnectAsync('127.0.0.1',$P); $ok=$t.Wait(500) -and $t.IsCompleted -and -not $t.IsFaulted; $c.Dispose(); return $ok } catch { return $false } }
function Label($obj,[string]$key) { if ($obj.Config.Labels) { $p=$obj.Config.Labels.PSObject.Properties | Where-Object Name -eq $key | Select-Object -First 1; if($p){return [string]$p.Value} }; return '' }
$canonical="$Project-$Service-1"; $owners=@(); $ids=@((Wsl @('docker','ps','-aq')) -split "`r?`n" | Where-Object { $_.Trim() })
foreach($id in $ids){ try{$o=(Wsl @('docker','inspect',$id.Trim()) | Out-String | ConvertFrom-Json)[0]}catch{continue}; if(-not $o.HostConfig.PortBindings){continue}; $hit=@($o.HostConfig.PortBindings.PSObject.Properties|ForEach-Object{if($_.Value){@($_.Value|Where-Object{[int]$_.HostPort -eq $Port})}}); if($hit.Count -eq 0){continue}; $name=([string]$o.Name).TrimStart('/'); $ownerProject=Label $o 'com.docker.compose.project'; $active=@($o.NetworkSettings.Ports.PSObject.Properties|ForEach-Object{if($_.Value){@($_.Value|Where-Object{[int]$_.HostPort -eq $Port})}}).Count -gt 0; $class=if($ownerProject -ne $Project){'OTHER_DOCKER_CONTAINER'}elseif($name -ne $canonical){'DUPLICATE_OJPLATFORM_CONTAINER'}elseif([string]$o.State.Status -eq 'running' -and $active){'EXPECTED_OJPLATFORM_CONTAINER'}elseif([string]$o.State.Status -eq 'exited'){ 'EXPECTED_OJPLATFORM_CONTAINER' }else{'STALE_OJPLATFORM_CONTAINER'}; $owners+=[pscustomobject]@{class=$class;id=$o.Id;name=$name;project=$ownerProject;service=(Label $o 'com.docker.compose.service');state=$o.State.Status} }
try{$listeners=@(Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction Stop)}catch{$listeners=@()}; if($listeners.Count){$l=$listeners[0];$p='unknown';try{$p=(Get-Process -Id $l.OwningProcess -ErrorAction Stop).ProcessName}catch{};throw "PORT_OWNED_BY_EXTERNAL_PROCESS: port=$Port pid=$($l.OwningProcess) process=$p"}
$wslListeners=@(Wsl @('ss','-ltnp') | Where-Object { $_ -match ":$Port\b" }); $wslExternal=@($wslListeners | Where-Object { $_ -notmatch 'docker-proxy|docker-pr' }); if($wslExternal.Count){$line=$wslExternal[0];$pidText='unknown';$processText='unknown';if($line -match 'users:\(\("([^"]+)",pid=(\d+)'){$processText=$Matches[1];$pidText=$Matches[2]};throw "PORT_OWNED_BY_EXTERNAL_PROCESS: port=$Port pid=$pidText process=$processText source=WSL"}
$other=@($owners|Where-Object class -eq 'OTHER_DOCKER_CONTAINER');if($other.Count){$o=$other[0];throw "PORT_OWNED_BY_OTHER_DOCKER_RESOURCE: port=$Port container=$($o.name) id=$($o.id.Substring(0,12)) project=$($o.project) service=$($o.service)"}
$expected=@($owners|Where-Object class -eq 'EXPECTED_OJPLATFORM_CONTAINER');if($expected.Count){$o=$expected[0];Write-Host "Port $Port owner=EXPECTED_OJPLATFORM_CONTAINER container=$($o.name)";return}
$stale=@($owners|Where-Object class -in @('STALE_OJPLATFORM_CONTAINER','DUPLICATE_OJPLATFORM_CONTAINER'));foreach($o in $stale){Write-Host "Port $Port owner=$($o.class) container=$($o.name)";try{Wsl @('docker','network','disconnect','-f',$Project,$o.id)|Out-Null}catch{};Wsl @('docker','rm','-f',$o.id)|Out-Null}
$wslProxy=@($wslListeners|Where-Object{$_ -match 'docker-proxy|docker-pr'});if($wslProxy.Count -and $owners.Count -eq 0){foreach($line in $wslProxy){if($line -match 'pid=(\d+)'){Write-Host "Port $Port owner=STALE_DOCKER_PORT_PROXY pid=$($Matches[1])";try{Wsl @('kill','-TERM',$Matches[1])|Out-Null}catch{}}}}
$cleanup=($stale.Count -gt 0 -or $wslProxy.Count -gt 0);if(Tcp $Port){$deadline=(Get-Date).AddSeconds(10);do{Start-Sleep -Milliseconds 250}while((Tcp $Port)-and((Get-Date)-lt $deadline));if(Tcp $Port){throw "PORT_OWNER_UNKNOWN: port=$Port evidence=targeted cleanup did not release listener"};Write-Host "Port $Port release VERIFIED"}elseif($cleanup){Write-Host "Port $Port release VERIFIED"}else{Write-Host "Port $Port owner=FREE"}
